### ISSUE TITLE
Doesn't work with system language other than English

### ISSUE THREAD

**Issue by Sophtli** [tantalising/plasma-accent-color-changer#2] opened 2021-08-21 13:41 UTC
I'm receiving the following error:

`#0      getCurrentlySetThemePath (package:kolorify/color_scheme_read_and_write_utils.dart:46)
<asynchronous suspension>
#1      generateColorScheme (package:kolorify/color_scheme_change_utils.dart:12)
<asynchronous suspension>
#2      applyColorScheme (package:kolorify/general_utils.dart:119)
<asynchronous suspension>
#3      ColorCard.handleTap (package:kolorify/color_grid_ui.dart:89)
<asynchronous suspension>`

That's probably because the output of `plasma-apply-colorscheme  --list-schemes` depends on the system language and in German the current color scheme will contain "(Aktuelles Farbschema)" as a suffix instead of the "(current color scheme)" that is searched for.

**Comment by tantalising** [comment] 2021-08-22 06:05
Yes you are right. That's the issue. Looks like I have to find a different way to get the current color scheme.

**Comment by tantalising** [comment] 2021-08-22 16:23
The issue is fixed now.

**Closed as completed by tantalising** 2021-08-22 16:23 UTC
